version: '2.0'

services:
  notebook:
    build:
      context: ../
      dockerfile: ./odor_meso/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/data/odor_meso/
      - ../DataPlot:/data/DataPlot/
      - ${EXTERNAL_MOUNT_MESO}:${MESO_STORAGE}
      - ${EXTERNAL_MOUNT_STACK}:${STACK_STORAGE}
      - ${EXTERNAL_MOUNT_SCRATCH10}:${SCRATCH10_STORAGE}
      - ${EXTERNAL_MOUNT_SCRATCH08}:${SCRATCH08_STORAGE}
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    entrypoint:
      - jupyter 
      - lab
      - --ip=0.0.0.0
      - --port=8888
      - --allow-root
      - --NotebookApp.token=''
      - --no-browser